services:
  db:
    image: postgres:17.0
    container_name: cea-pgdb
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${VOLUMES_ROOT}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: cea-app
    command: uvicorn cea.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ${VOLUMES_ROOT}/logs:/code/${PROJECT_USER:-cea}/cea/logs
    ports:
      - '8000:8000'
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
