"""init tables

Revision ID: c4968d13fe0b
Revises: 
Create Date: 2025-09-19 17:46:05.952539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4968d13fe0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cur_abbr', sa.String(), nullable=False),
    sa.Column('cur_scale', sa.Integer(), nullable=False),
    sa.Column('cur_rate', sa.Float(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_date', 'cur_abbr', name='uq_rate_date_abbr')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('amount_from', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount_to', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cur_from', sa.String(length=8), nullable=False),
    sa.Column('cur_to', sa.String(length=8), nullable=False),
    sa.Column('rate_from', sa.Float(), nullable=True),
    sa.Column('scale_from', sa.Integer(), nullable=True),
    sa.Column('rate_to', sa.Float(), nullable=True),
    sa.Column('scale_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
